### ISSUE TITLE
-

### ISSUE THREAD

**Issue by derimagia** [CleverbotIO/node-cleverbot.io#10]

**Comment by dtesler** [comment]
response data is on Algolia, can't exactly open-source that as Algolia is proprietary software.

**Comment by derimagia** [comment]
Sounds like you should remove the "Open Source" text then?

**Comment by dtesler** [comment]
We don't have any control over Algolia unfortunately as they're a separate company.

**Comment by yousefamar** [comment]
Not sure why this issue was nuked, but I had the conversation sitting in my email and from what I can tell @derimagia is absolutely right. While I don't care about the server code myself, could you explain to me (somebody who has never used Algolia) what exactly you mean by not releasing server source code?

From [what I can tell](https://www.algolia.com/doc/guides/getting-started/how-it-works#frontend-implementation), you're not interfacing with Algolia directly, but you have some server sitting in the middle. Surely the interfacing part with Algolia's servers/APIs is not proprietary? If there are any API keys or so, you can move them into some gitignore'd config file, and release the rest.

When it comes to proprietary libs, with open source backend code, or indeed any code that uses them, it's standard practice to not include those libs in your repo, but instead pull them from somewhere compile-time depending on what build system you're using (Ruby stuff in this case?). Even if you're not using any, the readme could straight up say "download these libs and move them to libs folder". Even still, most of the proprietary libs will have some clause to allow redistribution of their binaries since anyway people can get those from them. So I don't exactly see what the problem is, and Dave's point seems to me entirely valid.

Have I misunderstood something? Are you running the actual server-side implementation of Algolia on your own servers somehow (in which case, refer to my second point)?
